### ISSUE TITLE
Crash after a few minutes of importing files

### ISSUE THREAD

**Issue by aaronjwood** [photoprism/photoprism#1139]
I was just going through a basic import workflow when I ran into a crash:
```
...
time="2021-03-20T08:25:40Z" level=info msg="folder: added album “June 2018” (path:2018/06 public:true)"
time="2021-03-20T08:25:40Z" level=info msg="import: created folder /2018/06"
time="2021-03-20T08:25:40Z" level=info msg="import: moving main jpg file DSC01559.JPG to 2018/06/20180623_181754_CDB31505.jpg"
time="2021-03-20T08:25:40Z" level=info msg="media: 14 thumbnails created for 20180528_182012_364AC75E [5.791153933s]"
time="2021-03-20T08:25:40Z" level=info msg="media: DSC01560.JPG was taken at 2018-06-23 18:18:16 +0000 UTC (meta)"
time="2021-03-20T08:25:41Z" level=info msg="import: moving main jpg file DSC01560.JPG to 2018/06/20180623_181816_10433CF5.jpg"
time="2021-03-20T08:25:41Z" level=info msg="media: 14 thumbnails created for 20180528_182022_4283EC93 [5.702425082s]"
time="2021-03-20T08:25:41Z" level=info msg="media: 20180528_182022_4283EC93.jpg was taken at 2018-05-28 18:20:22 +0000 UTC (meta)"
time="2021-03-20T08:25:41Z" level=info msg="media: 20180528_182012_364AC75E.jpg was taken at 2018-05-28 18:20:12 +0000 UTC (meta)"
time="2021-03-20T08:25:41Z" level=info msg="import: added main jpg file 2018/05/20180528_182022_4283EC93.jpg"
time="2021-03-20T08:25:41Z" level=info msg="import: added main jpg file 2018/05/20180528_182012_364AC75E.jpg"
time="2021-03-20T08:25:41Z" level=info msg="media: DSC01561.JPG was taken at 2018-06-23 18:21:53 +0000 UTC (meta)"
time="2021-03-20T08:25:41Z" level=info msg="media: DSC01562.JPG was taken at 2018-06-23 18:24:17 +0000 UTC (meta)"
time="2021-03-20T08:25:41Z" level=info msg="import: moving main jpg file DSC01561.JPG to 2018/06/20180623_182153_9079DDAC.jpg"
time="2021-03-20T08:25:41Z" level=info msg="import: moving main jpg file DSC01562.JPG to 2018/06/20180623_182417_281B45AE.jpg"
time="2021-03-20T08:25:45Z" level=info msg="media: 14 thumbnails created for 20180528_182919_0F09AFCF [4.665477862s]"
time="2021-03-20T08:25:45Z" level=info msg="media: 20180528_182919_0F09AFCF.jpg was taken at 2018-05-28 18:29:19 +0000 UTC (meta)"
time="2021-03-20T08:25:45Z" level=info msg="media: 14 thumbnails created for 20180528_182445_2E809C6B [5.201287989s]"
time="2021-03-20T08:25:45Z" level=info msg="media: 20180528_182445_2E809C6B.jpg was taken at 2018-05-28 18:24:45 +0000 UTC (meta)"
time="2021-03-20T08:25:46Z" level=info msg="import: added main jpg file 2018/05/20180528_182919_0F09AFCF.jpg"
time="2021-03-20T08:25:46Z" level=info msg="media: 14 thumbnails created for 20180528_182149_D9698E94 [5.448827232s]"
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5db25d]

goroutine 72 [running]:
encoding/json.(*encodeState).marshal.func1(0xc0016f7478)
        /usr/local/go/src/encoding/json/encode.go:328 +0x8d
panic(0xf60ee0, 0x17ded50)
        /usr/local/go/src/runtime/panic.go:965 +0x1b9
encoding/json.(*encodeState).string(0xc005adc200, 0x0, 0x5, 0x1)
        /usr/local/go/src/encoding/json/encode.go:1033 +0x5d
encoding/json.stringEncoder(0xc005adc200, 0xf1c8a0, 0xc000eeab08, 0x198, 0x100)
        /usr/local/go/src/encoding/json/encode.go:647 +0x1d6
encoding/json.structEncoder.encode(0xc023e00900, 0xf, 0x10, 0xc023cf4270, 0xc005adc200, 0x103ce00, 0xc000eeab00, 0x199, 0x4c0100)
        /usr/local/go/src/encoding/json/encode.go:761 +0x2ab
encoding/json.ptrEncoder.encode(0xc023cf42a0, 0xc005adc200, 0x10252e0, 0xc00001fab0, 0x196, 0x100)
        /usr/local/go/src/encoding/json/encode.go:944 +0x125
encoding/json.structEncoder.encode(0xc0013e0600, 0x37, 0x43, 0xc023cf4690, 0xc005adc200, 0x10630a0, 0xc00001f8c0, 0x199, 0x100)
        /usr/local/go/src/encoding/json/encode.go:761 +0x2ab
encoding/json.arrayEncoder.encode(0xc023cf46c0, 0xc005adc200, 0xf0b9a0, 0xc0047b4060, 0x97, 0xc023cf0100)
        /usr/local/go/src/encoding/json/encode.go:915 +0xd6
encoding/json.sliceEncoder.encode(0xc000bbf470, 0xc005adc200, 0xf0b9a0, 0xc0047b4060, 0x97, 0xf00100)
        /usr/local/go/src/encoding/json/encode.go:888 +0xfe
encoding/json.(*encodeState).reflectValue(0xc005adc200, 0xf0b9a0, 0xc0047b4060, 0x97, 0xc0047b0100)
        /usr/local/go/src/encoding/json/encode.go:360 +0x82
encoding/json.interfaceEncoder(0xc005adc200, 0xf44dc0, 0xc005a1e760, 0x94, 0xc005a10100)
        /usr/local/go/src/encoding/json/encode.go:716 +0xac
encoding/json.mapEncoder.encode(0x10f01f0, 0xc005adc200, 0xf80000, 0xc000ee8750, 0x15, 0xf80100)
        /usr/local/go/src/encoding/json/encode.go:813 +0x366
encoding/json.(*encodeState).reflectValue(0xc005adc200, 0xf80000, 0xc000ee8750, 0x15, 0xc000ee0100)
        /usr/local/go/src/encoding/json/encode.go:360 +0x82
encoding/json.interfaceEncoder(0xc005adc200, 0xf44dc0, 0xc005a1e740, 0x94, 0xc005a10100)
        /usr/local/go/src/encoding/json/encode.go:716 +0xac
encoding/json.mapEncoder.encode(0x10f01f0, 0xc005adc200, 0xf7f780, 0xc000a4c960, 0x15, 0xf70100)
        /usr/local/go/src/encoding/json/encode.go:813 +0x366
encoding/json.(*encodeState).reflectValue(0xc005adc200, 0xf7f780, 0xc000a4c960, 0x15, 0xc0016f0100)
        /usr/local/go/src/encoding/json/encode.go:360 +0x82
encoding/json.(*encodeState).marshal(0xc005adc200, 0xf7f780, 0xc000a4c960, 0xf70100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:332 +0xf9
encoding/json.(*Encoder).Encode(0xc005edf540, 0xf7f780, 0xc000a4c960, 0x7efdec50a400, 0xc000a4c990)
        /usr/local/go/src/encoding/json/stream.go:206 +0x8b
github.com/gorilla/websocket.(*Conn).WriteJSON(0xc000153ce0, 0xf7f780, 0xc000a4c960, 0x4, 0xc001050518)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.2/json.go:28 +0xf2
github.com/photoprism/photoprism/internal/api.wsWriter(0xc000153ce0, 0xc000552698, 0xc0001a5470, 0x24)
        /go/src/github.com/photoprism/photoprism/internal/api/websocket.go:141 +0x6bd
created by github.com/photoprism/photoprism/internal/api.Websocket.func1
        /go/src/github.com/photoprism/photoprism/internal/api/websocket.go:189 +0x205
```

My environment is a VM with 12 GB RAM and 20 cores assigned to it. I have PHOTOPRISM_WORKERS set to 10, otherwise I run out of memory pretty quick.

**Comment by lastzero** [comment]
Try reducing `PHOTOPRISM_WORKERS` further and/or make sure you have swap configured. For 20 cores, you should at least have 20 GB of RAM.

**Comment by graciousgrey** [comment]
@aaronjwood did reducing the workers help?

**Comment by aaronjwood** [comment]
It helped in another case where the OOM killer was kicking in. That was a different error entirely as the application would receive a SIGKILL. For this specific error I haven't been able to reproduce it. I don't think it was due to being out of memory when I last encountered it but I have no way to confirm that right now.

AFAIK on Linux as a worst case when you're out of memory the OOM killer will kick in unless overcommit is disabled. In case of it being disabled brk() will fail with some error code indicating an out of memory condition and return a null pointer. Since I have been hitting OOMs due to having my worker count too high I don't believe this segfault should have been caused by a memory allocation failure.
