### ISSUE TITLE
Segfault on initial import

### ISSUE THREAD

**Issue by gcushen** [photoprism/photoprism#139]
Indexing stops due to panic. I haven't looked at the source refs below yet but it appears that it may have been caused by a long filename (60 chars alphanumeric with total of 90 chars rel path length)?

`sudo docker exec -ti photoprism photoprism index`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c9f4e7]

goroutine 1 [running]:
github.com/photoprism/photoprism/internal/photoprism.(*MediaFile).Filename(...)
	/go/src/github.com/photoprism/photoprism/internal/photoprism/mediafile.go:310
github.com/photoprism/photoprism/internal/photoprism.(*MediaFile).Basename(0x0, 0x3b609c0, 0x400)
	/go/src/github.com/photoprism/photoprism/internal/photoprism/mediafile.go:372 +0x27
github.com/photoprism/photoprism/internal/photoprism.(*Indexer).indexMediaFile(0xc0004d6c60, 0x0, 0x0, 0x0)
	/go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:111 +0xb7
github.com/photoprism/photoprism/internal/photoprism.(*Indexer).IndexRelated(0xc0004d6c60, 0xc0003f00a0, 0xc0003f00a0)
	/go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:359 +0xa1
github.com/photoprism/photoprism/internal/photoprism.(*Indexer).IndexAll.func1(0xc006497450, 0x4f, 0x2681e20, 0xc006d585b0, 0x0, 0x0, 0xd1891a, 0xc006d585b0)
	/go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:397 +0xe0
path/filepath.walk(0xc006497450, 0x4f, 0x2681e20, 0xc006d585b0, 0xc0004d6c80, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:358 +0x426
path/filepath.walk(0xc003b52e60, 0x41, 0x2681e20, 0xc0004b0270, 0xc0004d6c80, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x300
path/filepath.walk(0xc000408690, 0x28, 0x2681e20, 0xc006d584e0, 0xc0004d6c80, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:382 +0x300
path/filepath.walk(0xc0000ae1b0, 0x23, 0x2681e20, 0xc000447450, 0xc0004d6c80, 0x0, 0x20)
	/usr/local/go/src/path/filepath/path.go:382 +0x300
path/filepath.Walk(0xc0000ae1b0, 0x23, 0xc0004d6c80, 0x21af2c0, 0xc0004d6c60)
	/usr/local/go/src/path/filepath/path.go:404 +0xff
github.com/photoprism/photoprism/internal/photoprism.(*Indexer).IndexAll(0xc0004d6c60, 0xc0004dd740)
	/go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:382 +0xb2
github.com/photoprism/photoprism/internal/commands.indexAction(0xc0002682c0, 0x0, 0x0)
	/go/src/github.com/photoprism/photoprism/internal/commands/index.go:45 +0x20b
github.com/urfave/cli.HandleAction(0x2090060, 0x23eebd0, 0xc0002682c0, 0xc0000b6300, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x2347886, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2368381, 0x18, 0x0, ...)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x996
github.com/urfave/cli.(*App).Run(0xc0003b41a0, 0xc0000ba000, 0x2, 0x2, 0x0, 0x0)
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6af
main.main()
	/go/src/github.com/photoprism/photoprism/cmd/photoprism/photoprism.go:35 +0x30d
```

**Comment by lastzero** [comment]
It's possible. Do you know what specific file / file name caused this? Can you send us a sample?

Our app fails fast right now to find potential issues. We're going to catch panics later so that import / indexing doesn't stop.

**Comment by gcushen** [comment]
One can attempt to reproduce the bug using the following relative path and filename: `0000/000000 - Xxxxxxxxxx Xxx/62057606dfe0886bdec542113ce78630658a6be84c5c74f17438dbbc.jpg`

**Comment by gcushen** [comment]
Also, if indexing fails, is it worth considering resuming indexing where it previously left off rather than having to start again each time? Perhaps easier for debugging too?

**Comment by lastzero** [comment]
@gcushen We'll add a panic handler in the final release so that indexing continues. Thanks for the additional information. Sounds like this is an issue with file name parsing!?

Finished another project yesterday - ready to continue with PhotoPrism soon :)

**Comment by lastzero** [comment]
@gcushen Does this bug still exist?

**Comment by lastzero** [comment]
I'll close this since we didn't get feedback and our code has improved a lot since the bug was reported.
