### ISSUE TITLE
People: Panic in dbscanClusterer.nearestWorker() when indexing

### ISSUE THREAD

**Issue by rickysarraf** [photoprism/photoprism#1478]
Since the last one week or so, from the time the new facial recognition code has been added to the `develop` branch, I have PhotoPrism consistently crashing during the `index -a` process.

```
photoprism_1  | time="2021-08-17T10:17:21Z" level=debug msg="moments: updated “Water, Ships & Boats” (public:true label:lakeside|water)"
photoprism_1  | time="2021-08-17T10:17:26Z" level=debug msg="moments: 934 albums saved as yaml files"
photoprism_1  | time="2021-08-17T10:17:26Z" level=info msg="faces: found 137 new markers"
photoprism_1  | panic: sync: negative WaitGroup counter
photoprism_1  | 
photoprism_1  | goroutine 7357 [running]:
photoprism_1  | sync.(*WaitGroup).Add(0xc00484d280, 0xffffffffffffffff)
photoprism_1  |         /usr/local/go/src/sync/waitgroup.go:74 +0x147
photoprism_1  | sync.(*WaitGroup).Done(...)
photoprism_1  |         /usr/local/go/src/sync/waitgroup.go:99
photoprism_1  | github.com/mpraski/clusters.(*dbscanClusterer).nearestWorker(0xc001f72ff0)
photoprism_1  |         /go/pkg/mod/github.com/mpraski/clusters@v0.0.0-20171016094157-18104487c312/dbscan.go:251 +0x230
photoprism_1  | created by github.com/mpraski/clusters.(*dbscanClusterer).startNearestWorkers
photoprism_1  |         /go/pkg/mod/github.com/mpraski/clusters@v0.0.0-20171016094157-18104487c312/dbscan.go:228 +0xdb
mariadb_1     | 2021-08-17 10:17:32 33 [Warning] Aborted connection 33 to db: 'photoprism' user: 'photoprism' host: '172.17.0.3' (Got an error reading communication packets)
mariadb_1     | 2021-08-17 10:17:33 30 [Warning] Aborted connection 30 to db: 'photoprism' user: 'photoprism' host: '172.17.0.3' (Got an error reading communication packets)
mariadb_1     | 2021-08-17 10:17:34 32 [Warning] Aborted connection 32 to db: 'photoprism' user: 'photoprism' host: '172.17.0.3' (Got an error reading communication packets)
mariadb_1     | 2021-08-17 10:17:34 31 [Warning] Aborted connection 31 to db: 'photoprism' user: 'photoprism' host: '172.17.0.3' (Got an error reading communication packets)
photoprism_photoprism_1 exited with code 0
```

**Comment by rickysarraf** [comment]
I have 4 workers configured on this box.

`PHOTOPRISM_WORKERS: 4`

This is an x86_64 machine:

```
Intel(R) Core(TM) i7-4510U CPU @ 2.00GHz
RAM: 8 GiB
```

**Comment by lastzero** [comment]
Development environments have experimental features enabled by default, you can disable them or the People feature as a temporary workaround. Feel free to debug this:

https://github.com/photoprism/photoprism/blob/develop/internal/photoprism/faces.go#L225

**Comment by rickysarraf** [comment]
Lowering down the workers to 2 let the process munch for much more time, which is kinda expected. The debug logs were a bit more verbose this time.

```
photoprism_1  | time="2021-08-17T12:33:55Z" level=debug msg="moments: 934 albums saved as yaml files"
photoprism_1  | time="2021-08-17T12:33:55Z" level=info msg="faces: found 161 new markers"
photoprism_1  | time="2021-08-17T12:33:57Z" level=error msg="faces: sync: WaitGroup is reused before previous Wait has returned (panic)\nstack: goroutine 3014 [running]:\nruntime/debug.Stack(0xc0042c9268, 0xf91440, 0x19b1160)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/photoprism/photoprism/internal/photoprism.(*Faces).Start.func1(0xc0042c9910)\n\t/go/src/github.com/photoprism/photoprism/internal/photoprism/faces.go:171 +0x5d\npanic(0xf91440, 0x19b1160)\n\t/usr/local/go/src/runtime/panic.go:971 +0x499\nsync.(*WaitGroup).Wait(0xc004761070)\n\t/usr/local/go/src/sync/waitgroup.go:132 +0xae\ngithub.com/mpraski/clusters.(*dbscanClusterer).nearest(0xc000cce3c0, 0x1, 0xc0042c9408, 0xc0014ffd58)\n\t/go/pkg/mod/github.com/mpraski/clusters@v0.0.0-20171016094157-18104487c312/dbscan.go:216 +0x15e\ngithub.com/mpraski/clusters.(*dbscanClusterer).run(0xc000cce3c0)\n\t/go/pkg/mod/github.com/mpraski/clusters@v0.0.0-20171016094157-18104487c312/dbscan.go:155 +0x16c\ngithub.com/mpraski/clusters.(*dbscanClusterer).Learn(0xc000cce3c0, 0xc00472e000, 0x6af, 0x955, 0x0, 0x0)\n\t/go/pkg/mod/github.com/mpraski/clusters@v0.0.0-20171016094157-18104487c312/dbscan.go:93 +0x1c5\ngithub.com/photoprism/photoprism/internal/photoprism.(*Faces).Start(0xc0042c99a0, 0xc000f06000, 0x0, 0x0)\n\t/go/src/github.com/photoprism/photoprism/internal/photoprism/faces.go:225 +0x2d3\ngithub.com/photoprism/photoprism/internal/workers.(*Meta).Start(0xc002fd7fb0, 0xdf8475800, 0x0, 0x0)\n\t/go/src/github.com/photoprism/photoprism/internal/workers/meta.go:131 +0x990\ngithub.com/photoprism/photoprism/internal/workers.StartMeta.func1(0xc0006c6190)\n\t/go/src/github.com/photoprism/photoprism/internal/workers/workers.go:78 +0x51\ncreated by github.com/photoprism/photoprism/internal/workers.StartMeta\n\t/go/src/github.com/photoprism/photoprism/internal/workers/workers.go:76 +0x57\n"
photoprism_1  | panic: sync: negative WaitGroup counter
photoprism_1  | 
photoprism_1  | goroutine 3326 [running]:
photoprism_1  | sync.(*WaitGroup).Add(0xc004761070, 0xffffffffffffffff)
photoprism_1  |         /usr/local/go/src/sync/waitgroup.go:74 +0x147
photoprism_1  | sync.(*WaitGroup).Done(...)
photoprism_1  |         /usr/local/go/src/sync/waitgroup.go:99
photoprism_1  | github.com/mpraski/clusters.(*dbscanClusterer).nearestWorker(0xc000cce3c0)
photoprism_1  |         /go/pkg/mod/github.com/mpraski/clusters@v0.0.0-20171016094157-18104487c312/dbscan.go:251 +0x230
photoprism_1  | created by github.com/mpraski/clusters.(*dbscanClusterer).startNearestWorkers
photoprism_1  |         /go/pkg/mod/github.com/mpraski/clusters@v0.0.0-20171016094157-18104487c312/dbscan.go:228 +0xdb
mariadb_1     | 2021-08-17 12:33:57 22 [Warning] Aborted connection 22 to db: 'photoprism' user: 'photoprism' host: '172.17.0.3' (Got an error reading communication packets)
mariadb_1     | 2021-08-17 12:33:57 21 [Warning] Aborted connection 21 to db: 'photoprism' user: 'photoprism' host: '172.17.0.3' (Got an error reading communication packets)
mariadb_1     | 2021-08-17 12:33:57 20 [Warning] Aborted connection 20 to db: 'photoprism' user: 'photoprism' host: '172.17.0.3' (Got an error reading communication packets)
mariadb_1     | 2021-08-17 12:33:59 19 [Warning] Aborted connection 19 to db: 'photoprism' user: 'photoprism' host: '172.17.0.3' (Got an error reading communication packets)
mariadb_1     | 2021-08-17 12:33:59 18 [Warning] Aborted connection 18 to db: 'photoprism' user: 'photoprism' host: '172.17.0.3' (Got an error reading communication packets)
photoprism_photoprism_1 exited with code 0
```

**Comment by lastzero** [comment]
Does it work with only 1 worker?

**Comment by lastzero** [comment]
Waiting for feedback from the maintainer(s)

**Comment by rickysarraf** [comment]
With a single worker, it worked proper.

**Comment by fonz-zz** [comment]
would this fork fix it?
https://github.com/okhowang/clusters/commit/5a83968bbd0e45a1244b7d1c39db4ecca6bfd9de

**Comment by lastzero** [comment]
Works for me, forked it so that we can fix other issues if needed.

**Comment by rickysarraf** [comment]
Tested with the latest `devel` tip with: `PHOTOPRISM_WORKERS: 4` workers. I can confirm that the changes fix the crash.

**Comment by Galliver7** [comment]
Probably I am getting same this issue...
Is there a way to test on docker?
I am using Image ID:0607578fcce1 now.

Btw, wanna know when will deploy ; )

**Comment by rickysarraf** [comment]
> Probably I am getting same this issue...
> Is there a way to test on docker?
> I am using Image ID:0607578fcce1 now.
> 
> Btw, wanna know when will deploy ; )

This should be fixed. I had validated it with the `devel` branch.
