### ISSUE TITLE
MySQL: Fix compatibility issues

### ISSUE THREAD

**Issue by halkeye** [photoprism/photoprism#1519]
Trying to run photoprism/photoprism:preview docker image and getting an error about table not existing. I've tried running migrate, I've tried deleting all the tables from the db. All the other tables seem to get created, but not the subjects_dev6 table

```
panic: Error 1146: Table 'photoprism.subjects_dev6' doesn't exist
```

There's no other error messages. I can't figure out how to enable any extra logging that might be able to help debugging.

**Comment by halkeye** [comment]
from a clean database

````
$ photoprism migrate
INFO[2021-09-10T03:15:03Z] migrating database
panic: Error 1146: Table 'photoprism.subjects_dev6' doesn't exist

goroutine 1 [running]:
github.com/jinzhu/gorm.mysql.HasIndex({{{0x18c1400, 0xc0012c2ea0}, {}}}, {0xf634b6, 0xd}, {0xc00160c940, 0x1e})
        /go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/dialect_mysql.go:189 +0x252
github.com/jinzhu/gorm.(*Scope).addIndex(0xc00167f380, 0x0, {0xc00160c940, 0x1e}, {0xc001699be0, 0x1, 0x87bb80})
        /go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/scope.go:1216 +0xa6
github.com/jinzhu/gorm.(*DB).AddIndex(0xc0016a8820, {0xc00160c940, 0x1e}, {0xc001699be0, 0x1, 0x1})
        /go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/main.go:711 +0x85
github.com/jinzhu/gorm.(*Scope).autoIndex(0xc00167f000)
        /go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/scope.go:1316 +0x365
github.com/jinzhu/gorm.(*Scope).createTable(0xc00167f000)
        /go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/scope.go:1198 +0x633
github.com/jinzhu/gorm.(*Scope).autoMigrate(0xc00167f000)
        /go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/scope.go:1269 +0xd6
github.com/jinzhu/gorm.(*DB).AutoMigrate(0xc000e9f888, {0xc000e9f878, 0x1, 0xc0070b0140})
        /go/pkg/mod/github.com/jinzhu/gorm@v1.9.16/main.go:689 +0x8e
github.com/photoprism/photoprism/internal/entity.Types.Migrate(0xc0070c8000)
        /go/src/github.com/photoprism/photoprism/internal/entity/entity.go:104 +0xc6
github.com/photoprism/photoprism/internal/entity.MigrateDb()
        /go/src/github.com/photoprism/photoprism/internal/entity/entity.go:139 +0x25
github.com/photoprism/photoprism/internal/config.(*Config).InitDb(0xc00001c230)
        /go/src/github.com/photoprism/photoprism/internal/config/db.go:239 +0x65
github.com/photoprism/photoprism/internal/commands.migrateAction(0xc00109a420)
        /go/src/github.com/photoprism/photoprism/internal/commands/migrate.go:33 +0x125
github.com/urfave/cli.HandleAction({0xe20240, 0x1658920}, 0x7)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8
github.com/urfave/cli.Command.Run({{0xf5527e, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0xf86f0b, 0x28}, {0x0, ...}, ...}, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x652
github.com/urfave/cli.(*App).Run(0xc0010aa1c0, {0xc0001a0000, 0x2, 0x2})
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x705
main.main()
        /go/src/github.com/photoprism/photoprism/cmd/photoprism/photoprism.go:79 +0x997
```

**Comment by halkeye** [comment]
okay, latest latest preview image gives me dev8 instead of dev6

**Comment by lastzero** [comment]
Why do you run migrate manually? Not needed. Should fix this anyway....

**Comment by halkeye** [comment]
testing/trying/etc

photoprism start did the same thing. its something todo with the automigrate

**Comment by lastzero** [comment]
Can you manually try to delete this table first?

**Comment by lastzero** [comment]
Don't need it anymore.

**Comment by halkeye** [comment]
The table doesn't exist.
```
I have no ***@***.***:/$ mysql -u root -p$MYSQL_ROOT_PASSWORD photoprism
-e 'show tables'
mysql: [Warning] Using a password on the command line interface can be
insecure.
+----------------------+
| Tables_in_photoprism |
+----------------------+
| accounts             |
| albums               |
| cameras              |
| categories           |
| cells                |
| countries            |
| details              |
| files                |
| files_share          |
| files_sync           |
| folders              |
| keywords             |
| labels               |
| lenses               |
| links                |
| passwords            |
| photos               |
| photos_albums        |
| photos_keywords      |
| photos_labels        |
| users                |
+----------------------+
```

I've tried entirely empty dbs. I'm not sure why the stacktrace mentions has
index. According to the code I dug through that should only happen if the
table exists. So maybe its being created in one transaction and not
committed or something?

**Comment by halkeye** [comment]
dev8 still seems to be used
https://github.com/photoprism/photoprism/blob/24107eef825c23de2e44b48def63010d00ac2da9/internal/entity/subject.go#L45

**Comment by halkeye** [comment]
AHA!

Used https://github.com/Plopix/docker-mysqlproxyprofiler to intercept the
mysql traffic and mysql is throwing an error


CREATE TABLE `subjects_dev8` (`subject_uid` VARBINARY(42),`thumb`
VARBINARY(128) DEFAULT '',`thumb_src` VARBINARY(8) DEFAULT
'',`subject_type` VARBINARY(8) DEFAULT '',`subject_src` VARBINARY(8)
DEFAULT '',`subject_slug` VARBINARY(255) DEFAULT '',`subject_name`
VARCHAR(255) DEFAULT '',`subject_alias` VARCHAR(255) DEFAULT
'',`subject_bio` TEXT DEFAULT '',`subject_notes` TEXT DEFAULT '',`favorite`
boolean DEFAULT false,`private` boolean DEFAULT false,`excluded` boolean
DEFAULT false,`file_count` int DEFAULT 0,`metadata_json`
MEDIUMBLOB,`created_at` DATETIME NULL,`updated_at` DATETIME
NULL,`deleted_at` DATETIME NULL , PRIMARY KEY (`subject_uid`)) "BLOB, TEXT,
GEOMETRY or JSON column 'subject_bio' can't have a default value"   <NONE>
 46.009000ms

**Comment by lastzero** [comment]
What specific database version is this? It's working in our test environments. Try changing the subject_bio column to see if it helps.

**Comment by halkeye** [comment]
looks like mysql 8.0.26

I'll try to made the code change this weekend and update accordingly

```
SHOW VARIABLES LIKE "%version%";'                                              
+--------------------------+-------------------------------+
| Variable_name            | Value                         |
+--------------------------+-------------------------------+
| admin_tls_version        | TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 |
| immediate_server_version | 999999                        |
| innodb_version           | 8.0.26                        |
| original_server_version  | 999999                        |
| protocol_version         | 10                            |
| replica_type_conversions |                               |
| slave_type_conversions   |                               |
| tls_version              | TLSv1,TLSv1.1,TLSv1.2,TLSv1.3 |
| version                  | 8.0.26                        |
| version_comment          | Source distribution           |
| version_compile_machine  | x86_64                        |
| version_compile_os       | Linux                         |
| version_compile_zlib     | 1.2.11                        |
+--------------------------+-------------------------------+
```

**Comment by lastzero** [comment]
Try mariadb as in our example docker-compose.yml

**Comment by halkeye** [comment]
Yea I'll try that too. I think I can probably swap over my server to mariadb without issue, i don't think my mysql server is used by much.

https://docs.photoprism.org/getting-started/ does say works with mysql 8 so its probably worth running tests with it.

This is all hypothetical though, I won't be able to play with it till after work

**Comment by lastzero** [comment]
It should. Docs are for our stable release, haven't tested facial recognition on MySQL yet. So thanks for reporting this!

**Comment by halkeye** [comment]
```
diff --git a/internal/entity/subject.go b/internal/entity/subject.go
index 18c2bdac..df624269 100644
--- a/internal/entity/subject.go
+++ b/internal/entity/subject.go
@@ -28,8 +28,8 @@ type Subject struct {
        SubjectSlug  string          `gorm:"type:VARBINARY(255);index;default:''" json:"Slug" yaml:"-"`
        SubjectName  string          `gorm:"type:VARCHAR(255);unique_index;default:''" json:"Name" yaml:"Name"`
        SubjectAlias string          `gorm:"type:VARCHAR(255);default:''" json:"Alias" yaml:"Alias"`
-       SubjectBio   string          `gorm:"type:TEXT;default:''" json:"Bio" yaml:"Bio,omitempty"`
-       SubjectNotes string          `gorm:"type:TEXT;default:''" json:"Notes,omitempty" yaml:"Notes,omitempty"`
+       SubjectBio   string          `gorm:"type:TEXT" json:"Bio" yaml:"Bio,omitempty"`
+       SubjectNotes string          `gorm:"type:TEXT" json:"Notes,omitempty" yaml:"Notes,omitempty"`
        Favorite     bool            `gorm:"default:false" json:"Favorite" yaml:"Favorite,omitempty"`
        Private      bool            `gorm:"default:false" json:"Private" yaml:"Private,omitempty"`
        Excluded     bool            `gorm:"default:false" json:"Excluded" yaml:"Excluded,omitempty"`
```

It allows it to run and create tables. I havn't tested anything yet though.

**Comment by halkeye** [comment]
Github doesn't let me know about commit messages. But I saw in the latest update this has been fixed, so I think this is safe to close.

**Comment by lastzero** [comment]
Yes, tested several times with MySQL 8 today.
