### ISSUE TITLE
Panic if select originals in the Library

### ISSUE THREAD

**Issue by ahkhystrix** [photoprism/photoprism#3187]
Hello!

I use latest version via docker-compose, about 150K photos, indexing is normal.
```
# docker image ls
REPOSITORY              TAG       IMAGE ID       CREATED        SIZE
mariadb                 10.9      e00804e67b3d   2 months ago   378MB
photoprism/photoprism   latest    e6f531bbf1b0   2 months ago   1.5GB
```

```
time="2023-02-10T07:34:56Z" level=info msg="server: listening on 0.0.0.0:2342 [2.354675ms]"


time="2023-02-10T07:35:11Z" level=debug msg="server: GET /api/v1/ws (200) [14.792934262s]"
time="2023-02-10T07:35:11Z" level=debug msg="server: GET /library/index (200) [3.085383ms]"
time="2023-02-10T07:35:12Z" level=debug msg="server: GET /api/v1/config (200) [1.015721872s]"
time="2023-02-10T07:35:12Z" level=debug msg="server: GET /api/v1/session/265d5ca02336364ace5d2_skiped (200) [1.070083237s]"
panic: failed to find terminating 0 byte in dirent

goroutine 124 [running]:
github.com/photoprism/photoprism/pkg/fastwalk.direntNamlen(0xc001caf8c0?)
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk_dirent_namlen_linux.go:26 +0x8d
github.com/photoprism/photoprism/pkg/fastwalk.parseDirEnt({0xc0039077b8?, 0x600?, 0xc003888510?})
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk_unix.go:118 +0x13b
github.com/photoprism/photoprism/pkg/fastwalk.readDir({0xc0024e7020, 0x28}, 0xc003907eb8)
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk_unix.go:47 +0x24c
github.com/photoprism/photoprism/pkg/fastwalk.(*walker).walk(0xc003807410?, {0xc0024e7020?, 0x28?}, 0x0?)
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk.go:195 +0xaf
github.com/photoprism/photoprism/pkg/fastwalk.(*walker).doWork(0xc003807410, 0x0?)
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk.go:134 +0x125
created by github.com/photoprism/photoprism/pkg/fastwalk.Walk
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk.go:81 +0x212
```

If I go to the library and try to look at the available originals for indexing, then an error occurs immediately.

**Comment by lastzero** [comment]
👉 https://github.com/golang/go/issues/50428

Does it also happen with our development preview build? See docs for how to update.

Make sure to use our bug report template next time and provide COMPLETE information, such as the operating system and filesystem you are using. Thank you! ❤️

**Comment by ahkhystrix** [comment]
I'm sorry:
- OS: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
- FS: XFS on server, access to original via SMB (CIFS on Windows Server)

"Does it also happen with our development preview build? See docs for how to update." - ОК, I'm trying it.

**Comment by lastzero** [comment]
This might also be relevant to you:

https://linux-cifs.vger.kernel.narkive.com/e5Bb8nQW/accented-characters-not-working-with-cifs-but-ok-with-smbclient

**Comment by ahkhystrix** [comment]
Hello, I've tried :preview image tag and have this problem:

```
panic: failed to find terminating 0 byte in dirent

goroutine 115 [running]:
github.com/photoprism/photoprism/pkg/fastwalk.direntNamlen(0xc00020d080?)
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk_dirent_namlen_linux.go:26 +0x8d
github.com/photoprism/photoprism/pkg/fastwalk.parseDirEnt({0xc00252d7b8?, 0x600?, 0xc001ef9710?})
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk_unix.go:118 +0x14b
github.com/photoprism/photoprism/pkg/fastwalk.readDir({0xc001e35500, 0x28}, 0xc00252deb8)
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk_unix.go:47 +0x24c
github.com/photoprism/photoprism/pkg/fastwalk.(*walker).walk(0xc002451b60?, {0xc001e35500?, 0x28?}, 0x0?)
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk.go:195 +0xaf
github.com/photoprism/photoprism/pkg/fastwalk.(*walker).doWork(0xc002451b60, 0x0?)
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk.go:134 +0x125
created by github.com/photoprism/photoprism/pkg/fastwalk.Walk
        /go/src/github.com/photoprism/photoprism/pkg/fastwalk/fastwalk.go:81 +0x212
```

Thanks for your link, I will check it.

**Comment by lastzero** [comment]
Note that Windows uses UCS2 (INCLUDES NULL CHARACTERS) while Linux software expects UTF8 (NO NULL CHARACTERS).

**Comment by ahkhystrix** [comment]
Tanks for your helpful!

I think I found the problem. Some directories are connected on CIFS from Windows to Linux. Where filenames are longer than 255 characters this error occurs.

I'm thinking about a solution, I don't want to impose a limit on the length of the file name (users).
