### ISSUE TITLE
runtime error: invalid memory address while trying to import photos from cifs/smb

### ISSUE THREAD

**Issue by SharkyRawr** [photoprism/photoprism#454]
Hi, I keep getting this error after a short while trying to import Photos from cifs:

```
2020-08-09 23:36:58 ERRO index: runtime error: invalid memory address or nil pointer dereference (panic) stack: goroutine 54 [running]: runtime/debug.Stack(0xc017b97fa8, 0xf27ec0, 0x1b19cd0) /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/photoprism/photoprism/internal/photoprism.(*Index).Start.func1() /go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:62 +0x66 panic(0xf27ec0, 0x1b19cd0) /usr/local/go/src/runtime/panic.go:969 +0x166
github.com/photoprism/photoprism/internal/photoprism.(*MediaFile).FileName(...) /go/src/github.com/photoprism/photoprism/internal/photoprism/mediafile.go:379
github.com/photoprism/photoprism/internal/photoprism.(*MediaFile).RelatedFiles(0xc0000d8a80, 0xc01806f100, 0x38, 0x103ba39, 0x1, 0x0, 0xed3bc9a75, 0x23b6560) /go/src/github.com/photoprism/photoprism/internal/photoprism/mediafile.go:316 +0xa13
github.com/photoprism/photoprism/internal/photoprism.(*Index).Start.func5(0xc01806f1d0, 0x4e, 0xc0135f3920, 0xc017b98830, 0x506ac2) /go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:164 +0x635
github.com/karrick/godirwalk.walk(0xc01806f1d0, 0x4e, 0xc0135f3920, 0xc017b990d0, 0x4e, 0x0) /go/pkg/mod/github.com/karrick/godirwalk@v1.15.6/walk.go:218 +0x69
github.com/karrick/godirwalk.walk(0xc013746440, 0x34, 0xc0188c2990, 0xc017b990d0, 0x34, 0x0) /go/pkg/mod/github.com/karrick/godirwalk@v1.15.6/walk.go:279 +0x424
github.com/karrick/godirwalk.walk(0xc018883830, 0x29, 0xc0183a6690, 0xc017b990d0, 0x29, 0x0) /go/pkg/mod/github.com/karrick/godirwalk@v1.15.6/walk.go:279 +0x424
github.com/karrick/godirwalk.walk(0xc01836d1a0, 0x24, 0xc01836ea50, 0xc017b990d0, 0x24, 0x0) /go/pkg/mod/github.com/karrick/godirwalk@v1.15.6/walk.go:279 +0x424
github.com/karrick/godirwalk.walk(0xc0152b6680, 0x1c, 0xc00e0308a0, 0xc017b990d0, 0x1c, 0x0) /go/pkg/mod/github.com/karrick/godirwalk@v1.15.6/walk.go:279 +0x424
github.com/karrick/godirwalk.walk(0xc013666000, 0x15, 0xc017ff5f20, 0xc017b990d0, 0x0, 0x0) /go/pkg/mod/github.com/karrick/godirwalk@v1.15.6/walk.go:279 +0x424
github.com/karrick/godirwalk.Walk(0xc013666000, 0x15, 0xc017b990d0, 0x0, 0x0) /go/pkg/mod/github.com/karrick/godirwalk@v1.15.6/walk.go:204 +0x238
github.com/photoprism/photoprism/internal/photoprism.(*Index).Start(0xc013562810, 0x103ba38, 0x1, 0x0, 0x0) /go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:116 +0x604
github.com/photoprism/photoprism/internal/api.StartIndexing.func1(0xc013736f00) /go/src/github.com/photoprism/photoprism/internal/api/index.go:60 +0x32c
github.com/gin-gonic/gin.(*Context).Next(0xc013736f00) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/photoprism/photoprism/internal/server.Recovery.func1(0xc013736f00) /go/src/github.com/photoprism/photoprism/internal/server/recovery.go:32 +0x4e
github.com/gin-gonic/gin.(*Context).Next(0xc013736f00) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/photoprism/photoprism/internal/server.Logger.func1(0xc013736f00) /go/src/github.com/photoprism/photoprism/internal/server/logger.go:18 +0x9a
github.com/gin-gonic/gin.(*Context).Next(0xc013736f00) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/context.go:161 +0x3b
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc000255680, 0xc013736f00) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:409 +0x666
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc000255680, 0x1254b40, 0xc0184e40e0, 0xc0152ee000) /go/pkg/mod/github.com/gin-gonic/gin@v1.6.3/gin.go:367 +0x14d
net/http.serverHandler.ServeHTTP(0xc0184e4b60, 0x1254b40, 0xc0184e40e0, 0xc0152ee000) /usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0002ae140, 0x1258ac0, 0xc01380ec80) /usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve /usr/local/go/src/net/http/server.go:2962 +0x35c
```
(edit 08/10: formatted stack trace to be more readable)

And the kernel.log shows: `CIFS VFS: Send error in read = -4` -- not sure if this is related but seems like it.

Using the docker version `photoprism/photoprism:latest` (image id `d26973e00988`) on Debian 10 `5.7.0-0.bpo.2-amd64` (but it also happens on Linux 5.5). CIFS is mounted with `vers=2.1` but it also happens on `vers=3`.  
I can access the mount otherwise fine and read and write files, everything else seems to work perfectly. The server-side of the mount is a Synology DS918+.  
Completely uncertain and stumped if this is a Golang, photoprism or CIFS issue or something completely different. :/

**Comment by lastzero** [comment]
Not sure if it's an issue with CIFS, but the nil pointer panic should be gone with the next Docker build. I'll go through some more issues and then merge to master, new images available later today.

**Comment by SharkyRawr** [comment]
Just tested with docker image id `d88ab63bd174` and the issue appears to be gone! Thanks!

Still getting a ton of CIFS VFS errors but those don't seem to have any impact on photoprism.
