### ISSUE TITLE
SIGSEGV when indexing photos on Linux

### ISSUE THREAD

**Issue by orsenthil** [photoprism/photoprism#88]
* I am on Ubuntu 18.10
*  Docker version

```
docker --version
Docker version 18.06.1-ce, build e68fc7a
```
* On a folder with around 249 items,

When running the command:

```
docker exec -ti photoprism photoprism index
```

I encountered this error SIGSEGV error.

```
No location: lat and long are missing in Exif metadata
Added main jpg file "IMG_20181221_065330_1.jpg"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x12acd66]

goroutine 1 [running]:
github.com/photoprism/photoprism/internal/photoprism.(*MediaFile).GetFilename(...)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/mediafile.go:391
github.com/photoprism/photoprism/internal/photoprism.(*MediaFile).GetCanonicalNameFromFile(0x0, 0xc00128a460, 0xc000477228)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/mediafile.go:268 +0x26
github.com/photoprism/photoprism/internal/photoprism.(*Indexer).indexMediaFile(0xc00000da80, 0x0, 0x1, 0x1)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:82 +0x9a
github.com/photoprism/photoprism/internal/photoprism.(*Indexer).IndexRelated(0xc00000da80, 0xc0000f66e0, 0xc0000f66e0)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:240 +0x9b
github.com/photoprism/photoprism/internal/photoprism.(*Indexer).IndexAll.func1(0xc0003df9b0, 0x2e, 0x1b32f60, 0xc00022e4e0, 0x0, 0x0, 0xd, 0xc000477828)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:278 +0x179
path/filepath.walk(0xc0003df9b0, 0x2e, 0x1b32f60, 0xc00022e4e0, 0xc00000dac0, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:358 +0x41c
path/filepath.walk(0xc000281040, 0x20, 0x1b32f60, 0xc00033e410, 0xc00000dac0, 0x0, 0x20)
        /usr/local/go/src/path/filepath/path.go:382 +0x2fe
path/filepath.Walk(0xc000281040, 0x20, 0xc00000dac0, 0x458267, 0xc000477a00)
        /usr/local/go/src/path/filepath/path.go:404 +0x105
github.com/photoprism/photoprism/internal/photoprism.(*Indexer).IndexAll(0xc00000da80, 0xc00000da80)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/indexer.go:263 +0x87
github.com/photoprism/photoprism/internal/commands.indexAction(0xc000274c60, 0x0, 0xc000274c60)
        /go/src/github.com/photoprism/photoprism/internal/commands/index.go:34 +0x25a
github.com/urfave/cli.HandleAction(0x1654600, 0x198efa0, 0xc000274c60, 0xc00008c400, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x18f04fb, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x190fc8e, 0x18, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x9a2
github.com/urfave/cli.(*App).Run(0xc00040e9c0, 0xc00000c060, 0x2, 0x2, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x687
main.main()
        /go/src/github.com/photoprism/photoprism/cmd/photoprism/photoprism.go:32 +0x2da
```

**Comment by orsenthil** [comment]
I am not sure if https://github.com/photoprism/photoprism/issues/36 is related. I bothered to raise this issue, and if this related to https://github.com/photoprism/photoprism/issues/36, please close this.

**Comment by lastzero** [comment]
Maybe, not sure. Thanks for reporting! If you like, you can test if it only happens with specific files and if yes, attach one to this ticket or send it to us: hello@photoprism.org

**Comment by lastzero** [comment]
Thank you, this is somewhat related to #56. PhotoPrism expects the filename to be canonical, that means it must have a certain length and must be unique.

Otherwise the function might return null and this is what happened. Canonical names get created during import when moving the file to originals. So we need to find a way to index files with random names without needing a canonical name. Nothing I can fix quickly...

**Comment by lastzero** [comment]
Fixed that AFAIK - let us know otherwise 👍
